/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CCP;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author Acer
 */
public class CaptainSignup extends javax.swing.JFrame {

    String DataBasePath = "jdbc:oracle:thin:@localhost:1521:XE";
    ImageIcon li = new ImageIcon("signup.png");
    private String VechicalColor;

    /**
     * Creates new form CAptainSignup
     */
    public CaptainSignup() {
        initComponents();
        this.setTitle("Captain SignUp");
        setLocationRelativeTo(null);
        signupicon.setText("");
        signupicon.setIcon(li);
//        setLocationRelativeTo(null);
        passnotmatch.setText("");
        useralreadyexist.setText("");

        inputPassword.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }
        });
        inputConfirmPassword.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }
        });
        inputuserfullname.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }
        });
        inputphonenumber.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }
        });
//        inputphonenumber.addFocusListener(new FocusListener() {
//
//            @Override
//            public void focusGained(FocusEvent e) {
//                passnotmatch.setText("");
//                useralreadyexist.setText("");
//            }
//
//            @Override
//            public void focusLost(FocusEvent e) {
//                passnotmatch.setText("");
//                useralreadyexist.setText("");
//            }
//        });
        enteruserusername.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        signupicon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inputuserfullname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        enteruserusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputConfirmPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        passnotmatch = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        signup = new javax.swing.JButton();
        SignIn = new javax.swing.JButton();
        inputphonenumber = new javax.swing.JTextField();
        useralreadyexist = new javax.swing.JLabel();
        loginPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        inputvehicalmake = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        inputvehicalcolor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        inputvehicalmodel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        selectvehicaltype = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        inputvehicalnumber = new javax.swing.JTextField();
        securityquestionlabel = new javax.swing.JLabel();
        securityquestion = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        securityanswer = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Welcome to RoadRangers ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Cab Service");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        signupicon.setText("signup pic");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Details:"));

        jLabel3.setText("Enter Full Name:");

        jLabel4.setText("Enter Username");

        jLabel5.setText("Enter Password:");

        jLabel6.setText("Confirm Password:");

        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });

        jLabel8.setText("Phone Number:");

        passnotmatch.setForeground(new java.awt.Color(255, 0, 0));
        passnotmatch.setText("password does not match");

        signup.setText("SignUp");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        SignIn.setText("SignIn");
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });

        inputphonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputphonenumberActionPerformed(evt);
            }
        });

        useralreadyexist.setForeground(new java.awt.Color(255, 0, 0));
        useralreadyexist.setText("user exist error");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputuserfullname)
                    .addComponent(enteruserusername)
                    .addComponent(inputConfirmPassword)
                    .addComponent(inputPassword)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passnotmatch))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputphonenumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(useralreadyexist)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputuserfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(useralreadyexist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enteruserusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passnotmatch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Captain Signup");

        javax.swing.GroupLayout loginPanel1Layout = new javax.swing.GroupLayout(loginPanel1);
        loginPanel1.setLayout(loginPanel1Layout);
        loginPanel1Layout.setHorizontalGroup(
            loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        loginPanel1Layout.setVerticalGroup(
            loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehical Details:"));

        jLabel9.setText("Enter Vehical Make:");

        jLabel10.setText("Enter Vehical Number:");

        inputvehicalcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputvehicalcolorActionPerformed(evt);
            }
        });

        jLabel11.setText("Enter Vehical Color:");

        inputvehicalmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputvehicalmodelActionPerformed(evt);
            }
        });

        jLabel12.setText("Select Vehical Type:");

        selectvehicaltype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bike", "Rickshaw", "Mini Ride", "AC Ride", "Premium Ride" }));
        selectvehicaltype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectvehicaltypeActionPerformed(evt);
            }
        });

        jLabel13.setText("Enter Model Number:");

        inputvehicalnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputvehicalnumberActionPerformed(evt);
            }
        });

        securityquestionlabel.setBackground(new java.awt.Color(196, 181, 129));
        securityquestionlabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        securityquestionlabel.setText("Securityquestion");

        securityquestion.setForeground(new java.awt.Color(102, 102, 102));
        securityquestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "what was your first car?", "what is your secret number?", "what is your favorite food?", "what is your lucky color?", "what is your dream place?" }));
        securityquestion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel15.setBackground(new java.awt.Color(196, 181, 129));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Answer:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputvehicalmake)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(inputvehicalcolor)
                    .addComponent(inputvehicalmodel)
                    .addComponent(selectvehicaltype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(securityquestion, 0, 273, Short.MAX_VALUE)
                    .addComponent(securityanswer)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(securityquestionlabel)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(inputvehicalnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputvehicalmake, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel10)
                .addGap(54, 54, 54)
                .addComponent(jLabel13)
                .addGap(7, 7, 7)
                .addComponent(inputvehicalmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputvehicalcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectvehicaltype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(securityquestionlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(securityquestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(securityanswer)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(inputvehicalnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(296, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(loginPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(signupicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signupicon))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private static int getCurrentTimeAsNumber() {
        SimpleDateFormat timeFormat = new SimpleDateFormat("HHmmssSSS");
        String currentTime = timeFormat.format(new Date());
        return Integer.parseInt(currentTime);
    }

    public String encryptPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(password.getBytes());
            byte[] digest = md.digest();
            StringBuilder sb = new StringBuilder();
            for (byte b : digest) {
                sb.append(String.format("%02x", b & 0xff));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
            return null;
        }
    }

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        int ID = getCurrentTimeAsNumber();
        String Fullname = inputuserfullname.getText();
        String username = enteruserusername.getText().toLowerCase();
        String firstpassword = new String(inputPassword.getPassword());
        String secondpassword = new String(inputConfirmPassword.getPassword());
        String phonenumber = inputphonenumber.getText();
        String vehicalmake = inputvehicalmake.getText();
        String vehicalnumber = inputvehicalnumber.getText();
        String vehicalModel = inputvehicalmodel.getText();
        String vehicalcolor = inputvehicalcolor.getText();
        String vehicaltype = (String) selectvehicaltype.getSelectedItem();
        int usertype = 1;
        
        String SecQuestion=(String) securityquestion.getSelectedItem();
        String Secans=securityanswer.getText().toLowerCase();

        if (Fullname.isEmpty() || username.isEmpty() || firstpassword.isEmpty()
                || secondpassword.isEmpty() || phonenumber.isEmpty()
                || phonenumber.isEmpty() || vehicalmake.isEmpty() || vehicalnumber.isEmpty()
                || vehicalModel.isEmpty() || vehicalcolor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill up form Properly");
        } else if (StringUtils.containsWhitespace(username)) {
            JOptionPane.showMessageDialog(this, "Username should not contain whitespaces");
        } else {
            Connection con = null;
            PreparedStatement pst = null;
            ResultSet rs = null;
            try {

                Class.forName("oracle.jdbc.driver.OracleDriver"); // Fixed driver class name
                String url = "jdbc:oracle:thin:@localhost:1521:XE";
                String usernamee = "system";
                String passwordd = "awansara123";
                con = DriverManager.getConnection(url, usernamee, passwordd);
                String query1 = "SELECT * FROM CAPTAINS WHERE Username = '" + username + "'";
                pst = con.prepareStatement(query1);
                rs = pst.executeQuery();

                if (rs.next()) {
                    useralreadyexist.setText("Username already taken.");
                    enteruserusername.setText("");

                } else {
                    if (!firstpassword.equals(secondpassword)) {
                        passnotmatch.setText("Password does not match");
                        inputPassword.setText("");
                        inputConfirmPassword.setText("");
                    } else if (firstpassword.equals(secondpassword)) {
                        String encryptedPassword = encryptPassword(firstpassword);
                        passnotmatch.setText("");

                        Class.forName("oracle.jdbc.driver.OracleDriver"); // Fixed driver class name

                        con = DriverManager.getConnection(url, usernamee, passwordd);
                        String query = "insert into CAPTAINS(FullName,Username,Password,PhoneNumber,UserType,VehicalMake,VehicalNumber,VehicalModel,VehicalColor,VehicalType, ID,SecurityQuestion,SecurityAnswer) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                        pst = con.prepareStatement(query);
                        pst.setString(1, Fullname);
                        pst.setString(2, username);
                        pst.setString(3, encryptedPassword);
                        pst.setString(4, phonenumber);
                        pst.setInt(5, usertype);
                        pst.setString(6, vehicalmake);
                        pst.setString(7, vehicalnumber);
                        pst.setString(8, vehicalModel);
                        pst.setString(9, vehicalcolor);
                        pst.setString(10, vehicaltype);
                        pst.setInt(11, ID);
                        pst.setString(12, SecQuestion);
                        pst.setString(13, Secans);
                        int rows = pst.executeUpdate();

                        if (rows > 0) {
                            JOptionPane.showMessageDialog(this, "SignUp Successful");
                            login_form lgf = new login_form();
                            lgf.show();
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "SignUp failed");
                        }
                    }
                }

            } catch (Exception e) {
                System.out.println(e);
            } finally {
                try {
                    if (con != null) {
                        con.close();
                    }
                    if (pst != null) {
                        pst.close();
                    }
                } catch (SQLException e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_signupActionPerformed

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
        // TODO add your handling code here:
        login_form lgf = new login_form();
        lgf.show();
        dispose();
    }//GEN-LAST:event_SignInActionPerformed

    private void inputvehicalcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputvehicalcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputvehicalcolorActionPerformed

    private void inputvehicalmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputvehicalmodelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputvehicalmodelActionPerformed

    private void selectvehicaltypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectvehicaltypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectvehicaltypeActionPerformed

    private void inputvehicalnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputvehicalnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputvehicalnumberActionPerformed

    private void inputphonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputphonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputphonenumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaptainSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaptainSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaptainSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaptainSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaptainSignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignIn;
    private javax.swing.JTextField enteruserusername;
    private javax.swing.JPasswordField inputConfirmPassword;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputphonenumber;
    private javax.swing.JTextField inputuserfullname;
    private javax.swing.JTextField inputvehicalcolor;
    private javax.swing.JTextField inputvehicalmake;
    private javax.swing.JTextField inputvehicalmodel;
    private javax.swing.JTextField inputvehicalnumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel loginPanel1;
    private javax.swing.JLabel passnotmatch;
    private javax.swing.JTextField securityanswer;
    private javax.swing.JComboBox securityquestion;
    private javax.swing.JLabel securityquestionlabel;
    private javax.swing.JComboBox selectvehicaltype;
    private javax.swing.JButton signup;
    private javax.swing.JLabel signupicon;
    private javax.swing.JLabel useralreadyexist;
    // End of variables declaration//GEN-END:variables
}
